title: The Walk Between Reality and Fantasy
description: Data Sprint on Generative AI and Fictionality
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air" # or "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
