title: The Walk Between Reality and Fantasy
description: Data Sprint on Generative AI and Fictionality
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
url: "https://ale66.github.io"
baseurl: "/the_walk"

# Author
author:
  name: "Workshop Organizers"
  bio: "Birkbeck, University of London"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
